export const streamingServices = [
  { id: 'abc', name: 'ABC' },
  { id: 'amazon', name: 'Amazon Prime Video' },
  { id: 'apple', name: 'Apple TV' },
  { id: 'britbox', name: 'BritBox' },
  { id: 'cbs', name: 'CBS' },
  { id: 'disney+', name: 'Disney+' },
  { id: 'discovery+', name: 'Discovery+' },
  { id: 'espn', name: 'ESPN' },
  { id: 'fox', name: 'Fox' },
  { id: 'hbo', name: 'HBO' },
  { id: 'hulu', name: 'Hulu' },
  { id: 'lifetime', name: 'Lifetime' },
  { id: 'max', name: 'Max' },
  { id: 'nbc', name: 'NBC' },
  { id: 'netflix', name: 'Netflix' },
  { id: 'paramount+', name: 'Paramount+' },
  { id: 'peacock', name: 'Peacock' },
  { id: 'philo', name: 'Philo' },
  { id: 'roku', name: 'Roku' },
  { id: 'sling', name: 'Sling TV' },
]